#!/bin/bash
# FrameIT Agent Installer — Raspberry Pi OS Lite
# Usage: curl -sSL {{ base_url }}/install.sh | bash -s -- --server <url> --token <token> [--user <username>]

set -euo pipefail

SERVER=""
TOKEN=""
KIOSK_USER="pi"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --server) SERVER="$2"; shift 2 ;;
        --token)  TOKEN="$2";  shift 2 ;;
        --user)   KIOSK_USER="$2"; shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

# ── Input validation ──────────────────────────────────────────────────────────

if [[ -z "$SERVER" || -z "$TOKEN" ]]; then
    echo "Usage: $0 --server <frameit-server-url> --token <registration-token> [--user <username>]"
    exit 1
fi

if [[ ! "$SERVER" =~ ^https?://[a-zA-Z0-9./_:-]+$ ]]; then
    echo "Error: --server must be a valid http/https URL."
    exit 1
fi

if [[ ! "$TOKEN" =~ ^[a-fA-F0-9]{64}$ ]]; then
    echo "Error: --token must be a 64-character hex string."
    exit 1
fi

if [[ ! "$KIOSK_USER" =~ ^[a-z_][a-z0-9_-]{0,31}$ ]]; then
    echo "Error: --user must be a valid Unix username."
    exit 1
fi

# ── Privilege check ───────────────────────────────────────────────────────────

if [[ "$EUID" -eq 0 ]]; then
    SUDO=""
else
    if ! command -v sudo &>/dev/null; then
        echo "Error: sudo is not installed. Install it or run as root."
        exit 1
    fi
    if ! sudo -v 2>/dev/null; then
        echo "Error: Current user does not have sudo privileges."
        exit 1
    fi
    SUDO="sudo"
fi

# Run a command as the kiosk user.
# Uses 'runuser' when already root, 'sudo -u' otherwise.
as_kiosk() {
    if [[ "$EUID" -eq 0 ]]; then
        runuser -u "$KIOSK_USER" -- "$@"
    else
        sudo -u "$KIOSK_USER" "$@"
    fi
}

# ── User check ────────────────────────────────────────────────────────────────

KIOSK_HOME=$(getent passwd "$KIOSK_USER" | cut -d: -f6)
if [[ -z "$KIOSK_HOME" ]]; then
    echo "Error: user '$KIOSK_USER' not found. Create the user first or pass --user <username>."
    exit 1
fi

AGENT_DIR="/opt/frameit-agent"
AGENT_PY="$AGENT_DIR/agent.py"
AGENT_VENV="$AGENT_DIR/venv"
KIOSK_SCRIPT="/usr/local/bin/frameit-kiosk.sh"
ENV_FILE="/etc/frameit-agent.env"
SUDOERS_FILE="/etc/sudoers.d/frameit-agent"
AGENT_SERVICE="/etc/systemd/system/frameit-agent.service"
UI_SERVICE="/etc/systemd/system/frameit-ui.service"

# ── Dependencies ──────────────────────────────────────────────────────────────
echo "==> Installing dependencies..."
$SUDO apt-get update -qq
$SUDO apt-get install -y --no-install-recommends \
    python3 \
    python3-venv \
    chromium-browser \
    xorg \
    x11-xserver-utils \
    openbox \
    unclutter \
    network-manager \
    curl \
    ca-certificates

# Switch from dhcpcd to NetworkManager for nmcli wifi support
if $SUDO systemctl is-enabled dhcpcd &>/dev/null; then
    echo "==> Switching network management to NetworkManager..."
    $SUDO systemctl disable dhcpcd --now || true
fi
$SUDO systemctl enable NetworkManager --now || true

# ── Sudoers ───────────────────────────────────────────────────────────────────
echo "==> Writing sudoers rules for '$KIOSK_USER'..."

$SUDO tee "$SUDOERS_FILE" > /dev/null <<EOF
# FrameIT Agent — sudo rules for $KIOSK_USER
# Generated by the FrameIT installer. Do not edit manually.

$KIOSK_USER ALL=(ALL) NOPASSWD: /sbin/reboot
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/apt-get update
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/apt-get upgrade -y
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl start frameit-ui
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl stop frameit-ui
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart frameit-ui
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/systemctl restart frameit-agent
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/hostnamectl set-hostname *
$KIOSK_USER ALL=(ALL) NOPASSWD: /usr/bin/nmcli dev wifi connect *
EOF

$SUDO chmod 440 "$SUDOERS_FILE"

# Validate the sudoers file — abort if syntax is wrong
if ! $SUDO visudo -c -f "$SUDOERS_FILE" &>/dev/null; then
    echo "Error: generated sudoers file failed validation. Removing."
    $SUDO rm -f "$SUDOERS_FILE"
    exit 1
fi

# ── Kiosk groups ──────────────────────────────────────────────────────────────
echo "==> Adding '$KIOSK_USER' to required groups..."
$SUDO usermod -a -G tty,video,input "$KIOSK_USER"

# ── Kiosk script ──────────────────────────────────────────────────────────────
echo "==> Writing kiosk script..."

$SUDO tee "$KIOSK_SCRIPT" > /dev/null <<KIOSKEOF
#!/bin/bash
export DISPLAY=:0

xset s off
xset -dpms
xset s noblank

unclutter -idle 1 -root &

openbox &
sleep 1

exec chromium-browser \\
    --kiosk \\
    --noerrdialogs \\
    --disable-infobars \\
    --disable-session-crashed-bubble \\
    --no-first-run \\
    --disable-translate \\
    --autoplay-policy=no-user-gesture-required \\
    --disable-features=Translate \\
    "$SERVER"
KIOSKEOF

$SUDO chmod +x "$KIOSK_SCRIPT"

# ── frameit-ui service ────────────────────────────────────────────────────────
echo "==> Installing frameit-ui service..."

$SUDO tee "$UI_SERVICE" > /dev/null <<EOF
[Unit]
Description=FrameIT Kiosk UI
After=frameit-agent.service systemd-user-sessions.service
Conflicts=getty@tty1.service

[Service]
User=$KIOSK_USER
TTYPath=/dev/tty1
StandardInput=tty
PAMName=login
UtmpIdentifier=tty1
UtmpMode=user
ExecStart=/usr/bin/xinit $KIOSK_SCRIPT -- /usr/bin/X :0 vt1 -nocursor -nolisten tcp
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

# ── Agent source + virtualenv ─────────────────────────────────────────────────
echo "==> Downloading FrameIT agent..."
$SUDO mkdir -p "$AGENT_DIR"
curl -fsSL "${SERVER}/agent.py"               | $SUDO tee "$AGENT_PY" > /dev/null
curl -fsSL "${SERVER}/agent-requirements.txt" | $SUDO tee "$AGENT_DIR/requirements.txt" > /dev/null
$SUDO chown -R "$KIOSK_USER:$KIOSK_USER" "$AGENT_DIR"
echo "==> Creating Python virtualenv..."
as_kiosk python3 -m venv "$AGENT_VENV"
as_kiosk "$AGENT_VENV/bin/pip" install --quiet -r "$AGENT_DIR/requirements.txt"
echo "    Installed to $AGENT_DIR"

# ── Environment config ────────────────────────────────────────────────────────
echo "==> Writing environment config..."

$SUDO tee "$ENV_FILE" > /dev/null <<EOF
FRAMEIT_SERVER=$SERVER
FRAMEIT_TOKEN=$TOKEN
AGENT_PORT=5001
KIOSK_USER=$KIOSK_USER
EOF

# Readable by the kiosk user only (contains the agent token)
$SUDO chown "root:$KIOSK_USER" "$ENV_FILE"
$SUDO chmod 640 "$ENV_FILE"

# ── frameit-agent service ─────────────────────────────────────────────────────
echo "==> Installing frameit-agent service..."

$SUDO tee "$AGENT_SERVICE" > /dev/null <<EOF
[Unit]
Description=FrameIT Agent
After=network-online.target
Wants=network-online.target

[Service]
User=$KIOSK_USER
EnvironmentFile=$ENV_FILE
ExecStart=$AGENT_VENV/bin/python $AGENT_PY
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

$SUDO systemctl daemon-reload
$SUDO systemctl enable frameit-agent frameit-ui
$SUDO systemctl restart frameit-agent
$SUDO systemctl start frameit-ui

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo "==> FrameIT installed and started."
echo "    Server:     $SERVER"
echo "    Kiosk user: $KIOSK_USER"
echo ""
echo "    Agent:  systemctl status frameit-agent"
echo "    Kiosk:  systemctl status frameit-ui"
